### ISSUE TITLE
Disable forced HTTPS

### ISSUE THREAD

**Issue by lesiki** [aworley/ocm#1]
First issue! 😄 

I'm running this locally and once I have the db config set up, I'm forcefully redirected to https. Is there any way I can disable this forcing of https and access my local instance over unsecured http? 

I see the changelog entry "Added redirect to https setting (forcing users to use https/ssl site) under system settings", but couldn't find out how to toggle this.

**Comment by aworley** [comment]
Congrats on your first post, so to speak.  :)  

To turn that option off, run the following SQL statement on the CMS database:

`update settings set value = '0' where label = 'force_https';`

Hope that helps.

**Comment by lesiki** [comment]
I actually meant _your_ first issue, on this repo :)

Thanks loads for this, will try it and be back to close if it works.

**Comment by lesiki** [comment]
This worked, thanks again.
