### ISSUE TITLE
SQL syntax error 

### ISSUE THREAD

**Issue by ebarrattMCEDSV** [aworley/ocm#16]
Hi I get this error when issuing cat /var/www/html/cms/app/sql/install/new_install.sql | mysql cms -u root -p

I installed this software once on premise and had no issues.

I'm currently working with a server in Azure, but I wouldnt think anything would change.

MariaDB version 5.5.60

ERROR 1064 (42000) at line 92: You have an error in your SQL syntax; check the m anual that corresponds to your MariaDB server version for the right syntax to use near 'JSON,
  PRIMARY KEY  (`case_id`),
  UNIQUE KEY `number` (`number`),
  KEY `clien' at line 110

**Comment by aworley** [comment]
Hello, thank you for letting us know about this.  As of the July 2nd 7.00 version release, the software now requires MySQL 5.7 or MariaDB 10.3.  If you attempt to install with an older version, you'll get that error message.

I realized that I had not updated the install instructions with that information, so I have done so, you can review the new docs here:  https://github.com/aworley/ocm/blob/master/README.md

Best,
Aaron
