### ISSUE TITLE
Prospective Client Search

### ISSUE THREAD

**Issue by kmiller101** [aworley/ocm#2]
Running this on a CentOS 7 machine with digitalocean. I'm a real novice! I receive an error message after clicking "Search" on the Prospective Client screen. Suggestions on how to fix this?

heres the debugging info:
FILE:                            /var/www/html/cms/app/lib/pikaMisc.php
LINE:                   539
SCREEN:                 NONE
ACTION:                 NONE
HTTP_REFERER:   NOT SET
REQUEST_METHOD: GET
REMOTE_ADDR:            69.128.217.86

HTTP_USER_AGENT:    Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

SERVER_NAME:    104.131.125.100

SERVER_SOFTWARE:    Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16

REQUEST URI:    /cms/intake2.php?first_name=Tim&middle_name=&last_name=Wilson&extra_name=&birth_date=&area_code=&phone=&ssn=&case_id=&number=&relation_code=&order_field=&order=&offset=&dmodes=Search+Names

QUERY STRING:   first_name=Tim&middle_name=&last_name=Wilson&extra_name=&birth_date=&area_code=&phone=&ssn=&case_id=&number=&relation_code=&order_field=&order=&offset=&dmodes=Search+Names

**Comment by aworley** [comment]
Hi Kris, thanks for the report.  Looks like there's a few lines missing from the install .sql file.  Try running ocm/cms/app/sql/upgrades/pika607_name_search.sql, then go to Site Map, then System Maintenance, then run the metaphone button, and hopefully that resolves the error.
