### ISSUE TITLE
User documentation?

### ISSUE THREAD

**Issue by wheeled** [aworley/ocm#24]
Is there a user documentation package associated with the OCM project?

**Comment by amsclark** [comment]
There is a Wiki:

https://github.com/aworley/ocm/wiki

Some of it is out of date but most is still relevant. I am starting to produce some videos at http://metatheria.solutions/ocm-training/ and am hoping to produce a comprehensive update to the documentation in 2020. If there are some specific things that are either not covered in the wiki or are confusing that you'd like to see documented first, let me know and I can prioritize them and try to put something together next week.

**Comment by wheeled** [comment]
Thanks, Alex.

For some reason I can access the wiki via the URL you sent but it does not appear in the list of files in GitHub.  Maybe it could be referenced in the readme file?

In any event I can see OCM is for legal case management and I was actually looking for something generic I could use for property case management in the NFP sector.  Any suggestions?  If so you can unicast me.

Regards, David
