### ISSUE TITLE
Error during dump of /var/www/html/cms/app/sql/new_install.sql

### ISSUE THREAD

**Issue by evanroot** [aworley/ocm#9]
When I did this I got the following 
```
[root@pikaocmp html]# cat /var/www/html/cms/app/sql/install/new_install.sql | mysql cms
ERROR 1067 (42000) at line 44: Invalid default value for 'ssn'

```
Is this issue a real problem?

**Comment by aworley** [comment]
Hi Evan, thanks for the heads up.  There was a missing comma in the file, looks like I removed it by accident when I modified the file on Mar 16.  I fixed it tonight and it works fine now.

AW

**Comment by evanroot** [comment]
Awsome!

Evan Root
Systems and Network Engineer,
SecureApps LLC
